{{- $fullName := include "hexagon.fullname" . -}}
# ============== ServiceAccount ==============
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "hexagon.labels" . | nindent 4 }}
automountServiceAccountToken: false
